
services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword1234
      POSTGRES_DB: mydb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    image: myapp
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge